# Generated by Django 4.2.4 on 2023-08-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usermodel_options_alter_usermodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=191, unique=True),
        ),
    ]
